package com.avhr.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.id
     *
     * @mbggenerated Sat Jul 23 01:11:40 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.name
     *
     * @mbggenerated Sat Jul 23 01:11:40 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.password
     *
     * @mbggenerated Sat Jul 23 01:11:40 CST 2016
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.age
     *
     * @mbggenerated Sat Jul 23 01:11:40 CST 2016
     */
    private String age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.id
     *
     * @return the value of User.id
     *
     * @mbggenerated Sat Jul 23 01:11:40 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.id
     *
     * @param id the value for User.id
     *
     * @mbggenerated Sat Jul 23 01:11:40 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.name
     *
     * @return the value of User.name
     *
     * @mbggenerated Sat Jul 23 01:11:40 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.name
     *
     * @param name the value for User.name
     *
     * @mbggenerated Sat Jul 23 01:11:40 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.password
     *
     * @return the value of User.password
     *
     * @mbggenerated Sat Jul 23 01:11:40 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.password
     *
     * @param password the value for User.password
     *
     * @mbggenerated Sat Jul 23 01:11:40 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.age
     *
     * @return the value of User.age
     *
     * @mbggenerated Sat Jul 23 01:11:40 CST 2016
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.age
     *
     * @param age the value for User.age
     *
     * @mbggenerated Sat Jul 23 01:11:40 CST 2016
     */
    public void setAge(String age) {
        this.age = age;
    }
}